language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: eV7yOyzurenZiQ4hc8B3l3MwpogkJWzeJHfyn/g/nS5rbGz5SnL6hFv+xITYgSTAAILS25WOc89r7x31pcvw16sxWSbAmA6r5nSSgePVEMKBbKwasTCwuzMtU3APl7nucv65OAlQ5FF3Q648YQQpdv+lWcFnQ3uPhanFpCxbPkHlVGR5gKEvPGKE61j7PkMNKkAJe5Et0rWgzqEw5ecOJE9BN2BD92Gq5WbKipDGqBuffFe/pT8bYnjf3wKvv/6zxC9ERL9Etr2mlLAMGpE+N/YxodKAyF5D9zqh3E+bASIM7+MX9PV2tqs/brz4XLL6espuRJchU85zPsmhO6cQWWncglw+u7taEsr6Hnd6t/oYWKSkD7wcDRZfbEtJkqqJFL2jr+MdM7JoGyLoQ1+NL6qSDQDrw+HmVHQPSSd/TUnU8CQ8yPDksvbc/5+EdBiWZxuReINiGEfjMpKav6SpMGtX7DiMLGmMSI/9VQRioUE18H3v0V2COMmd/vhqyNEbVZa7DmUBYl4nU8O7si0tSN0Ct8Pm54lRo7O4iaUrsfft6Ju5uHhsqNLP7DQz6aS89auT+xNqE4gULrpHlbZZ3WMh1J+da99hltltY9huD/JljZjMELxiL91JWvaSonR0LR5S4IfeaZGcHfe9p05s03IBmk/pHDJFIAJB3QKw2dA=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- yarn test
script:
- yarn run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
